modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Adds new sculk-themed hostile mobs to Minecraft.
'''
authors = "BlueDuck"

[[dependencies.blighted_beasts]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blighted_beasts]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blighted_beasts]]
modId = "geckolib"
type = "required"
versionRange = "[4.7,)"
ordering = "AFTER"
side = "BOTH"